### ISSUE TITLE
Scijava port: ImageJ2 migration

### ISSUE THREAD

**Issue by tferr** [fiji/Simple_Neurite_Tracer#30]
This is to log the ImageJ2 migration efforts. The work is starting on [my scijava branch](https://github.com/tferr/Simple_Neurite_Tracer/tree/scijava).

Braking changes:
- [x] Applet support will be dropped (Is anyone using it?)
- [x] IJ1 macro support will be dropped. Was flimsily and not that useful
- [x] All classes no longer in use from the virtual fly brain project will be deprecated
- [x] Support for old 3D viewer will be dropped in favor of SciView (see #22, kephale/ThreeDViewer#42)

Other changes:
- [x]  Reduce IJ1 dependencies (see also #29)
- [x]  Reduce VIB-lib dependencies (no longer maintained?)
- [x]  Allow ops filtering (Tubeness and Frangi ops are about to be released, see  imagej/imagej-ops#490)
- [x]  Allow tracing on any pre-filtered image
- [x]  Multichannel support (see #13)
- [x]  Proper scripting support
- [x]  API documentation (currently there is _zero_ javadoc documentation)
