### ISSUE TITLE
SciView TODO

### ISSUE THREAD

**Issue by kephale** [fiji/Simple_Neurite_Tracer#55]
- [x] Syncing multiple times duplicates nodes in SciView (see https://github.com/scenerygraphics/sciview/issues/215)
- [x] After SciView is closed,  pressing `Sync Changes` (or performing an operation triggering a sync call) will continue to sync changes to the _closed_ SciView Viewer.. Actually buttons in the SciView panel should update after SciView is closed.
- [ ] Volumes are not aligned (Note: this situation occurs when SNT populates a trace in SciView then "Add Volume" is used to open the image. Suggested alternative is to open a trace with a target image, which can be done via https://github.com/fiji/Simple_Neurite_Tracer/blob/137b36b0be2c9a080f87ffc5e8ce859ff5357e36/src/main/java/sc/fiji/snt/SNT.java#L1939)
- [ ] Consider disabling the inspector and disable SciJava events

**Comment by tferr** [comment]
So all the syncing occurs [here](https://github.com/fiji/Simple_Neurite_Tracer/blob/8bb352832354e5b1e363aaa107c57386f6c34e78/src/main/java/sc/fiji/snt/SNT.java#L2364-L2378). Looking at the call hierarchy, it seems it gets called _every time_ a node is added to the AWT image!! One thing I can do is to avoid syncing sciview (and reconstruction viewer for that matter) when calling `updateAllViewers()`. What do you think @kephale ?

**Comment by kephale** [comment]
A quick fix might be to just track when all viewers were last updated, and if that time is greater than some threshold, then try to refresh sciview and/or reconstruction viewer.

**Comment by tferr** [comment]
Just for reference: With db9962528 and 561efba968c35a things seem really more snappier. The logic is as follows:
- Split viewers in two categories: 1) Tracing viewers: Image canvas and legacy 3D viewer and 2) Non-tracing viewers: Rec. Viewer and SciView
- Rec. Viewer and SciView will only be refreshed when operations on _complete_ paths are performed. Un-confirmed and temporary paths from A* search will not appear in non-tracing viewers.
This may cause some UI inconsistency but the performance gains are worth it in my opinion

**Comment by kephale** [comment]
Also, opening multiple sciviews before the requested one opens (e.g. smashing the open sciview button) crashes the whole imagej

**Comment by tferr** [comment]
@kephale, one thing that ca13470cd02c does not address is that the "Open SciView Viewer" button keeps being disabled after SciView is closed, ie., the user does not have a way to re-open SciView after closing it. If a window listener is involved, quick workarounds would be:
1) Never disable the button (just display a warning if user clicks on it with viewer already being displayed)
2) Re-enable the button after displaying the dialog triggered by  pressing the Sync button with SciView is closed
What do you think? (let me known, I'm good at the easy stuff :smile: )

**Comment by kephale** [comment]
Hehe, check gitter :D

I think the easy thing is to never disable the button, but I was asking where the code for disabling the button is, then I'll take a look at it.

**Comment by kephale** [comment]
One more TODO:
Add a command that will turn on the SciView update site and call it from SNTLoaderCmd's isSciViewAvailable

**Comment by ctrueden** [comment]
Do you want to ship SciView with Fiji? It would simplify the SNT code, no?

**Comment by kephale** [comment]
@ctrueden Yes, it would be good to ship SciView with Fiji soon. I'd like to do a little more testing but we should really bite the bullet and just do it soon. What sort of things should we be looking at testing?

That said, there are only a few places where we have to deal with checking update site information. A lot of the other stuff we have been dealing with in SNT is about syncing SciView and SNT.
